[project]
name = "dagster-celery-k8s-oci"
version = "1.11.0"
description = "dagster-celery-k8s OCI image for Dagster deployments"
readme = "README.md"
requires-python = "~=3.13"
dependencies = [
    "dagster==1.11.0",
    "dagster-aws==0.27.0",
    "dagster-celery==0.27.0",
    "dagster-celery-k8s==0.27.0",
    "dagster-dbt==0.27.0",
    "dagster-embedded-elt==0.27.0",
    "dagster-graphql==1.11.0",
    "dagster-k8s==0.27.0",
    "dagster-postgres==0.27.0",
    "dagster-pyspark==0.27.0",
    "dagster-spark==0.27.0",
    "dagster-ssh==0.27.0",
    "dagster-webserver==1.11.0",
]
