name: Build and Tag Docker Image

on:
  push:
    branches: [main]
    paths:
      - "uv.lock"
      - "pyproject.toml"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract dagster version from pyproject.toml
        id: versionSelector
        run: |
          TAG_VERSION=$(sed -n -E 's/version = "([0-9.]+)"/\1/p' pyproject.toml)
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

          if [[ ! -z "$(docker images -q ghcr.io/${{ github.repository }}:$TAG_VERSION)" ]]; then
            echo "Skipping version $TAG_VERSION: it already exists."
            echo "skipBuild=TRUE" >> $GITHUB_OUTPUT
          fi

          echo "skipBuild=FALSE" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          pull: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.TAG_VERSION }}
          build-args: |
            TAG_VERSION=${{ env.TAG_VERSION }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
        if: ${{ needs.versionSelector.outputs.skipBuild != 'TRUE' }}
